#!/usr/bin/env bash
alias xsc="xclip -selection clipboard"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

#!/usr/bin/env bash
alias vim="$VIM"

alias ibrew="arch -x86_64 /usr/local/bin/brew"
alias mbrew='arch -arm64e /opt/homebrew/bin/brew'

alias python="python3"
alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias ebp="$VIM $DOTFILES/.zsh_profile"
alias yolo="git push origin master --force --no-verify"
