XDG_CONFIG_HOME=${HOME}/.config
DOTFILES=${HOME}/src/dotfiles
GARDEN_LOG_DIR=${HOME}/src/garden-log
PATH=${HOME}/.local/share/mise/shims:${HOME}/.local/bin:${PATH}
XDG_CURRENT_DESKTOP=sway
MOZ_ENABLE_WAYLAND=1
