gui:
  # UI settings similar to lazygit
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  language: 'auto'
  theme:
    lightTheme: false
    activeBorderColor:
      - green
    inactiveBorderColor:
      - blue
    optionsTextColor:
      - black
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - blue
  mouseEvents: true
  showAllContainers: false
  returnImmediately: false
  wrapMainPanel: true
  dockerHost: ''  # Leave empty to use current Docker context

logs:
  timestamps: false
  since: '60m'
  tail: ''

commandTemplates:
  dockerCompose: docker compose
  restartService: '{{ .DockerCompose }} restart {{ .Service.Name }}'
  up: '{{ .DockerCompose }} up -d'
  down: '{{ .DockerCompose }} down'
  downWithVolumes: '{{ .DockerCompose }} down --volumes'
  upService: '{{ .DockerCompose }} up -d {{ .Service.Name }}'
  viewLogs: '{{ .DockerCompose }} logs --since=60m --follow'
  viewLogsService: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  rebuildService: '{{ .DockerCompose }} up -d --build {{ .Service.Name }}'
  recreateService: '{{ .DockerCompose }} up -d --force-recreate {{ .Service.Name }}'
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow'
  viewAlLogs: '{{ .DockerCompose }} logs'
  dockerComposeConfig: '{{ .DockerCompose }} config'
  checkDockerComposeConfig: '{{ .DockerCompose }} config --quiet'
  serviceTop: '{{ .DockerCompose }} top {{ .Service.Name }}'

customCommands:
  containers:
    - name: bash
      attach: true
      command: docker exec -it {{ .Container.ID }} /bin/bash
      serviceNames: []
    - name: sh
      attach: true
      command: docker exec -it {{ .Container.ID }} /bin/sh
      serviceNames: []

oS:
  openCommand: open {{filename}}
  openLinkCommand: open {{link}}

stats:
  graphs:
    - caption: CPU (%)
      statPath: DerivedStats.CPUPercentage
      color: blue
    - caption: Memory (%)
      statPath: DerivedStats.MemoryPercentage
      color: green

confirmOnQuit: false
quitOnTopLevelReturn: true

keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    gotoTop: '<'
    gotoBottom: '>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextMatch: 'n'
    prevMatch: 'N'
    optionMenu: 'x'
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirm-alt1: 'y'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeCommand: ':'
    createOptionsMenu: 'm'
    refresh: 'R'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<c-z>'
    filteringMenu: '<c-s>'
    diffingMenu: 'W'
    diffingMenu-alt: '<c-e>'
    copyToClipboard: '<c-o>'
    submitEditorText: '<enter>'
    appendNewline: '<a-enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
    openInBrowser: 'o'
    viewDockerCompose: 'D'
  containers:
    pause: 'p'
    stop: 's'
    restart: 'r'
    start: 'u'
    attachShell: 'E'
    attachCommand: 'a'
    viewLogs: 'L'
    viewLogsOptions: 'O'
    scrollUpLogs: 'J'
    scrollDownLogs: 'K'
    rebuild: 'R'
    recreate: 'c'
    viewStats: 'S'
    runCustomCommand: 'C'
    bulkCommand: 'b'
    dockerComposeUp: 'U'
    dockerComposeDown: 'D'
    dockerComposeDownWithVolumes: 'V'
  services:
    pause: 'p'
    stop: 's'
    restart: 'r'
    start: 'u'
    recreate: 'c'
    rebuild: 'R'
    viewLogs: 'L'
    viewLogsOptions: 'O'
    dockerComposeUp: 'U'
    dockerComposeDown: 'D'
    dockerComposeDownWithVolumes: 'V'
    attachShell: 'E'
    attachCommand: 'a'
    runCustomCommand: 'C'
    bulkCommand: 'b'
    viewDockerComposeConfig: 'C'
  images:
    removeImage: 'd'
    runImage: 'r'
    viewDockerfile: 'D'
    pruneImages: 'P'
    pruneExited: 'x'
    pruneUntagged: 'T'
    pruneWithoutConfirm: '<c-p>'
  volumes:
    removeVolume: 'd'
    pruneVolumes: 'P'
    pruneWithoutConfirm: '<c-p>'
  main:
    viewAllLogs: 'a'
    allLogs: 'A'
    scrollUpLogs: 'J'
    scrollDownLogs: 'K'
    scrollUpLogs-alt: '<c-u>'
    scrollDownLogs-alt: '<c-d>'
    toggleFullscreen: 'f'