#!/usr/bin/env bash

target_name=$1
shift

branch_name=$(basename "$target_name")
session_name=$(tmux display-message -p "#S")
clean_name=$(echo "$branch_name" | tr "./" "__")
target="$session_name:$clean_name"

if ! tmux has-session -t "$target" 2> /dev/null; then
    tmux neww -dn "$clean_name"
fi

# Support: `tmux-windowizer client send-keys C-c C-c`
if [[ "$1" == "send-keys" ]]; then
    shift
    tmux send-keys -t "$target" "$@"
else
    tmux send-keys -t "$target" "$*" C-m
fi
