lastupdatecheck: 0
recentrepos:
    - /home/jonco/src/resume
    - /home/jonco/src/garden-logger
    - /home/jonco/src/dotfiles
startuppopupversion: 0
didshowhunkstaginghint: true
lastversion: 0.54.2
customcommandshistory:
    - q
hidecommandlog: false
