#!/usr/bin/env bash
# Case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"


# Show completion menu on ambiguous completion
setopt AUTO_MENU
setopt COMPLETE_IN_WORD

# Arrow keys for history search
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

# Basic arrow key bindings
bindkey '^[[C' forward-char
bindkey '^[[D' backward-char

# Don't match hidden files unless pattern starts with dot
setopt GLOB_DOTS

# Show file type indicators in completion
setopt LIST_TYPES

# Complete from both ends of word
setopt COMPLETE_IN_WORD

# Vim Mode
bindkey -v

export KEYTIMEOUT=1

bindkey -M vicmd 'k' up-line-or-beginning-search
bindkey -M vicmd 'j' down-line-or-beginning-search

# Key bindings for history navigation
bindkey '^k' up-line-or-beginning-search
bindkey '^j' down-line-or-beginning-search

# Use vim keys in tab complete menu:
bindkey -M menuselect '^h' vi-backward-char
bindkey -M menuselect '^k' vi-up-line-or-history
bindkey -M menuselect '^l' vi-forward-char
bindkey -M menuselect '^j' vi-down-line-or-history
bindkey -M menuselect '^[[Z' vi-up-line-or-history
bindkey -v '^?' backward-delete-char

# Edit command line in $EDITOR
autoload edit-command-line
zle -N edit-command-line
bindkey "^G" edit-command-line

# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}

zle -N zle-keymap-select
zle-line-init() {
    # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    zle -K viins
    echo -ne "\e[5 q"
}

zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.

preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.
