#!/usr/bin/env zsh
################################################################################
# Exported Variables
################################################################################

export XDG_CONFIG_HOME=$HOME/.config

# First items are added first, but referred to last - first in, last out.
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$ZDOTDIR/bin:$PATH

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred programs
export EDITOR="nvim"
export TERMINAL="kitty"
export MANPAGER='nvim +Man!'

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

export DOCKER_FOLDER="$HOME/src/docker/"
export HOSTNAME="hostname"
