#!/usr/bin/env bash
#------------------------------------------------------------------------------
# Profile
#------------------------------------------------------------------------------

export LANG=en_US.UTF-8
export MANPAGER='nvim +Man!'
export CC="clang"
export CXX="clang++"

export GOPATH=$HOME/.local/go
export GIT_EDITOR=$EDITOR

export ZSH_PLUGINS_DIR=/usr/share/zsh/plugins

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

export DOCKER_FOLDER="$HOME/src/docker/"

bindkey -s ^f "tmux-sessionizer\n"
bindkey -s '\eh' "tmux-sessionizer -s 0\n"
bindkey -s '\ej' "tmux-sessionizer -s 1\n"
bindkey -s '\ek' "tmux-sessionizer -s 2\n"
bindkey -s '\el' "tmux-sessionizer -s 3\n"

source $XDG_CONFIG_HOME/zsh/config/alias
source $XDG_CONFIG_HOME/zsh/config/docker
source $XDG_CONFIG_HOME/zsh/config/opt
source $XDG_CONFIG_HOME/zsh/config/helpers
source $XDG_CONFIG_HOME/zsh/config/fzf

addToPath $HOME/.npm-global/bin
addToPathFront $HOME/.local/bin
addToPath $ZDOTDIR/bin:$PATH

source ~/.config/zsh/theme/rose-pine-man.zsh

